[project]
name = "languagelearning"
version = "1.1.1"
description = "Webpage for learning German."
dependencies = [
    "flask",
    "pymongo",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"